version: '3'

services:
  redis:
    image: redis:alpine
    labels:
      - 'traefik.enable=false'
    networks:
      - devNet
    ports:
      - 6379
  mongo:
    container_name: mongo
    image: mongo:4.2.1-bionic
    restart: always
    ports:
      - '27018:27017'
    networks:
      - backend
  app:
    container_name: stamperBackend
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - MONGODB_URL=mongodb://mongo:27017/Stamper
      - CLIENT_URL=${CLIENT_URL}
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge
  devNet:
    driver: bridge
  mongo:
    driver: bridge
